// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: bluetooth_msg.proto

package bluetooth_schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_Unknown    MsgType = 0
	MsgType_Unlock     MsgType = 2
	MsgType_LockScreen MsgType = 3
	MsgType_Shutdown   MsgType = 4
	MsgType_Standby    MsgType = 5
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "Unknown",
		2: "Unlock",
		3: "LockScreen",
		4: "Shutdown",
		5: "Standby",
	}
	MsgType_value = map[string]int32{
		"Unknown":    0,
		"Unlock":     2,
		"LockScreen": 3,
		"Shutdown":   4,
		"Standby":    5,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_bluetooth_msg_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_bluetooth_msg_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_bluetooth_msg_proto_rawDescGZIP(), []int{0}
}

type ShutdownType int32

const (
	ShutdownType_E_UNKNOWN ShutdownType = 0
	// E=>通用
	ShutdownType_E_LOGOFF         ShutdownType = 1 // 注销当前用户
	ShutdownType_E_FORCE_SHUTDOWN ShutdownType = 2 // 强制关闭所有应用程序并关机 在Windows上即 (EWX_SHUTDOWN | EWX_FORCE)
	ShutdownType_E_FORCE_REBOOT   ShutdownType = 3 // 强制关闭所有应用程序并重启 在Windows上即(EWX_REBOOT | EWX_FORCE)
	// EWX => Windows 专有
	ShutdownType_EWX_SHUTDOWN                          ShutdownType = 4  // 关机但不关闭电源
	ShutdownType_EWX_REBOOT                            ShutdownType = 5  // 重启计算机
	ShutdownType_EWX_POWEROFF                          ShutdownType = 6  // 关机并关闭电源
	ShutdownType_EWX_HYBRID_SHUTDOWN                   ShutdownType = 7  // 混合关机
	ShutdownType_EWX_FORCE_POWEROFF                    ShutdownType = 8  // 强制关闭所有应用程序并关机同时关闭电源 (EWX_POWEROFF | EWX_FORCE)
	ShutdownType_EWX_REBOOT_RESTARTAPPS                ShutdownType = 9  // 重启计算机并重启应用程序 (EWX_REBOOT | EWX_RESTARTAPPS)
	ShutdownType_EWX_FORCE_REBOOT_RESTARTAPPS          ShutdownType = 10 // 强制关闭应用程序后重启并重启应用程序 (EWX_REBOOT | EWX_FORCE | EWX_RESTARTAPPS)
	ShutdownType_EWX_SHUTDOWN_RESTARTAPPS              ShutdownType = 11 // 关机但不关闭电源，关机后重启应用程序 (EWX_SHUTDOWN | EWX_RESTARTAPPS)
	ShutdownType_EWX_HYBRID_SHUTDOWN_FORCE             ShutdownType = 12 // 混合关机并强制关闭应用程序 (EWX_HYBRID_SHUTDOWN | EWX_FORCE)
	ShutdownType_EWX_HYBRID_SHUTDOWN_RESTARTAPPS       ShutdownType = 13 // 混合关机并重启应用程序 (EWX_HYBRID_SHUTDOWN | EWX_RESTARTAPPS)
	ShutdownType_EWX_HYBRID_SHUTDOWN_FORCE_RESTARTAPPS ShutdownType = 14 // 混合关机、强制关闭应用程序并重启应用程序 (EWX_HYBRID_SHUTDOWN | EWX_FORCE | EWX_RESTARTAPPS
)

// Enum value maps for ShutdownType.
var (
	ShutdownType_name = map[int32]string{
		0:  "E_UNKNOWN",
		1:  "E_LOGOFF",
		2:  "E_FORCE_SHUTDOWN",
		3:  "E_FORCE_REBOOT",
		4:  "EWX_SHUTDOWN",
		5:  "EWX_REBOOT",
		6:  "EWX_POWEROFF",
		7:  "EWX_HYBRID_SHUTDOWN",
		8:  "EWX_FORCE_POWEROFF",
		9:  "EWX_REBOOT_RESTARTAPPS",
		10: "EWX_FORCE_REBOOT_RESTARTAPPS",
		11: "EWX_SHUTDOWN_RESTARTAPPS",
		12: "EWX_HYBRID_SHUTDOWN_FORCE",
		13: "EWX_HYBRID_SHUTDOWN_RESTARTAPPS",
		14: "EWX_HYBRID_SHUTDOWN_FORCE_RESTARTAPPS",
	}
	ShutdownType_value = map[string]int32{
		"E_UNKNOWN":                             0,
		"E_LOGOFF":                              1,
		"E_FORCE_SHUTDOWN":                      2,
		"E_FORCE_REBOOT":                        3,
		"EWX_SHUTDOWN":                          4,
		"EWX_REBOOT":                            5,
		"EWX_POWEROFF":                          6,
		"EWX_HYBRID_SHUTDOWN":                   7,
		"EWX_FORCE_POWEROFF":                    8,
		"EWX_REBOOT_RESTARTAPPS":                9,
		"EWX_FORCE_REBOOT_RESTARTAPPS":          10,
		"EWX_SHUTDOWN_RESTARTAPPS":              11,
		"EWX_HYBRID_SHUTDOWN_FORCE":             12,
		"EWX_HYBRID_SHUTDOWN_RESTARTAPPS":       13,
		"EWX_HYBRID_SHUTDOWN_FORCE_RESTARTAPPS": 14,
	}
)

func (x ShutdownType) Enum() *ShutdownType {
	p := new(ShutdownType)
	*p = x
	return p
}

func (x ShutdownType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShutdownType) Descriptor() protoreflect.EnumDescriptor {
	return file_bluetooth_msg_proto_enumTypes[1].Descriptor()
}

func (ShutdownType) Type() protoreflect.EnumType {
	return &file_bluetooth_msg_proto_enumTypes[1]
}

func (x ShutdownType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShutdownType.Descriptor instead.
func (ShutdownType) EnumDescriptor() ([]byte, []int) {
	return file_bluetooth_msg_proto_rawDescGZIP(), []int{1}
}

type BluetoothPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求序列号，由客户端生成，服务端响应时必须原样返回
	// 用于客户端将响应与请求进行匹配
	SequenceId uint64 `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	// 使用 oneof 来确保一个包内要么是请求，要么是响应
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*BluetoothPacket_Request
	//	*BluetoothPacket_Response
	Payload       isBluetoothPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BluetoothPacket) Reset() {
	*x = BluetoothPacket{}
	mi := &file_bluetooth_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BluetoothPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BluetoothPacket) ProtoMessage() {}

func (x *BluetoothPacket) ProtoReflect() protoreflect.Message {
	mi := &file_bluetooth_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BluetoothPacket.ProtoReflect.Descriptor instead.
func (*BluetoothPacket) Descriptor() ([]byte, []int) {
	return file_bluetooth_msg_proto_rawDescGZIP(), []int{0}
}

func (x *BluetoothPacket) GetSequenceId() uint64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *BluetoothPacket) GetPayload() isBluetoothPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BluetoothPacket) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Payload.(*BluetoothPacket_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *BluetoothPacket) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Payload.(*BluetoothPacket_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isBluetoothPacket_Payload interface {
	isBluetoothPacket_Payload()
}

type BluetoothPacket_Request struct {
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type BluetoothPacket_Response struct {
	Response *Response `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*BluetoothPacket_Request) isBluetoothPacket_Payload() {}

func (*BluetoothPacket_Response) isBluetoothPacket_Payload() {}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_bluetooth_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_bluetooth_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_bluetooth_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MsgType                `protobuf:"varint,1,opt,name=type,proto3,enum=bluetooth_schema.MsgType" json:"type,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Request_UnlockMsg
	//	*Request_ShutdownMsg
	Body          isRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_bluetooth_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_bluetooth_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_bluetooth_msg_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_Unknown
}

func (x *Request) GetBody() isRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetUnlockMsg() *UnlockMsg {
	if x != nil {
		if x, ok := x.Body.(*Request_UnlockMsg); ok {
			return x.UnlockMsg
		}
	}
	return nil
}

func (x *Request) GetShutdownMsg() *ShutdownMsg {
	if x != nil {
		if x, ok := x.Body.(*Request_ShutdownMsg); ok {
			return x.ShutdownMsg
		}
	}
	return nil
}

type isRequest_Body interface {
	isRequest_Body()
}

type Request_UnlockMsg struct {
	UnlockMsg *UnlockMsg `protobuf:"bytes,2,opt,name=unlockMsg,proto3,oneof"`
}

type Request_ShutdownMsg struct {
	ShutdownMsg *ShutdownMsg `protobuf:"bytes,3,opt,name=shutdownMsg,proto3,oneof"`
}

func (*Request_UnlockMsg) isRequest_Body() {}

func (*Request_ShutdownMsg) isRequest_Body() {}

type UnlockMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockMsg) Reset() {
	*x = UnlockMsg{}
	mi := &file_bluetooth_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockMsg) ProtoMessage() {}

func (x *UnlockMsg) ProtoReflect() protoreflect.Message {
	mi := &file_bluetooth_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockMsg.ProtoReflect.Descriptor instead.
func (*UnlockMsg) Descriptor() ([]byte, []int) {
	return file_bluetooth_msg_proto_rawDescGZIP(), []int{3}
}

func (x *UnlockMsg) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UnlockMsg) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ShutdownMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ShutdownType           `protobuf:"varint,1,opt,name=type,proto3,enum=bluetooth_schema.ShutdownType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownMsg) Reset() {
	*x = ShutdownMsg{}
	mi := &file_bluetooth_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownMsg) ProtoMessage() {}

func (x *ShutdownMsg) ProtoReflect() protoreflect.Message {
	mi := &file_bluetooth_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownMsg.ProtoReflect.Descriptor instead.
func (*ShutdownMsg) Descriptor() ([]byte, []int) {
	return file_bluetooth_msg_proto_rawDescGZIP(), []int{4}
}

func (x *ShutdownMsg) GetType() ShutdownType {
	if x != nil {
		return x.Type
	}
	return ShutdownType_E_UNKNOWN
}

var File_bluetooth_msg_proto protoreflect.FileDescriptor

var file_bluetooth_msg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x5f, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74, 0x68,
	0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0xae, 0x01, 0x0a, 0x0f, 0x42, 0x6c, 0x75, 0x65,
	0x74, 0x6f, 0x6f, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74,
	0x68, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x30, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xc0, 0x01, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74, 0x68,
	0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x4d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x6c, 0x75, 0x65, 0x74,
	0x6f, 0x6f, 0x74, 0x68, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x55, 0x6e, 0x6c, 0x6f,
	0x63, 0x6b, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x09, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x4d,
	0x73, 0x67, 0x12, 0x41, 0x0a, 0x0b, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x4d, 0x73,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f,
	0x6f, 0x74, 0x68, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64,
	0x6f, 0x77, 0x6e, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x4d, 0x73, 0x67, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x43, 0x0a,
	0x09, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x41, 0x0a, 0x0b, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x4d, 0x73,
	0x67, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1e, 0x2e, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x5f, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x4d, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x6f, 0x63,
	0x6b, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x68, 0x75,
	0x74, 0x64, 0x6f, 0x77, 0x6e, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x62, 0x79, 0x10, 0x05, 0x2a, 0x85, 0x03, 0x0a, 0x0c, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x5f, 0x4c, 0x4f, 0x47, 0x4f, 0x46, 0x46,
	0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x5f, 0x46, 0x4f, 0x52, 0x43, 0x45, 0x5f, 0x53, 0x48,
	0x55, 0x54, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x5f, 0x46, 0x4f,
	0x52, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x42, 0x4f, 0x4f, 0x54, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c,
	0x45, 0x57, 0x58, 0x5f, 0x53, 0x48, 0x55, 0x54, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x04, 0x12, 0x0e,
	0x0a, 0x0a, 0x45, 0x57, 0x58, 0x5f, 0x52, 0x45, 0x42, 0x4f, 0x4f, 0x54, 0x10, 0x05, 0x12, 0x10,
	0x0a, 0x0c, 0x45, 0x57, 0x58, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x4f, 0x46, 0x46, 0x10, 0x06,
	0x12, 0x17, 0x0a, 0x13, 0x45, 0x57, 0x58, 0x5f, 0x48, 0x59, 0x42, 0x52, 0x49, 0x44, 0x5f, 0x53,
	0x48, 0x55, 0x54, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x07, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x57, 0x58,
	0x5f, 0x46, 0x4f, 0x52, 0x43, 0x45, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x4f, 0x46, 0x46, 0x10,
	0x08, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x57, 0x58, 0x5f, 0x52, 0x45, 0x42, 0x4f, 0x4f, 0x54, 0x5f,
	0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x41, 0x50, 0x50, 0x53, 0x10, 0x09, 0x12, 0x20, 0x0a,
	0x1c, 0x45, 0x57, 0x58, 0x5f, 0x46, 0x4f, 0x52, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x42, 0x4f, 0x4f,
	0x54, 0x5f, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x41, 0x50, 0x50, 0x53, 0x10, 0x0a, 0x12,
	0x1c, 0x0a, 0x18, 0x45, 0x57, 0x58, 0x5f, 0x53, 0x48, 0x55, 0x54, 0x44, 0x4f, 0x57, 0x4e, 0x5f,
	0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x41, 0x50, 0x50, 0x53, 0x10, 0x0b, 0x12, 0x1d, 0x0a,
	0x19, 0x45, 0x57, 0x58, 0x5f, 0x48, 0x59, 0x42, 0x52, 0x49, 0x44, 0x5f, 0x53, 0x48, 0x55, 0x54,
	0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x46, 0x4f, 0x52, 0x43, 0x45, 0x10, 0x0c, 0x12, 0x23, 0x0a, 0x1f,
	0x45, 0x57, 0x58, 0x5f, 0x48, 0x59, 0x42, 0x52, 0x49, 0x44, 0x5f, 0x53, 0x48, 0x55, 0x54, 0x44,
	0x4f, 0x57, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x41, 0x50, 0x50, 0x53, 0x10,
	0x0d, 0x12, 0x29, 0x0a, 0x25, 0x45, 0x57, 0x58, 0x5f, 0x48, 0x59, 0x42, 0x52, 0x49, 0x44, 0x5f,
	0x53, 0x48, 0x55, 0x54, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x46, 0x4f, 0x52, 0x43, 0x45, 0x5f, 0x52,
	0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x41, 0x50, 0x50, 0x53, 0x10, 0x0e, 0x42, 0x14, 0x5a, 0x12,
	0x2e, 0x3b, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x5f, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bluetooth_msg_proto_rawDescOnce sync.Once
	file_bluetooth_msg_proto_rawDescData = file_bluetooth_msg_proto_rawDesc
)

func file_bluetooth_msg_proto_rawDescGZIP() []byte {
	file_bluetooth_msg_proto_rawDescOnce.Do(func() {
		file_bluetooth_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_bluetooth_msg_proto_rawDescData)
	})
	return file_bluetooth_msg_proto_rawDescData
}

var file_bluetooth_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bluetooth_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bluetooth_msg_proto_goTypes = []any{
	(MsgType)(0),            // 0: bluetooth_schema.MsgType
	(ShutdownType)(0),       // 1: bluetooth_schema.ShutdownType
	(*BluetoothPacket)(nil), // 2: bluetooth_schema.BluetoothPacket
	(*Response)(nil),        // 3: bluetooth_schema.Response
	(*Request)(nil),         // 4: bluetooth_schema.Request
	(*UnlockMsg)(nil),       // 5: bluetooth_schema.UnlockMsg
	(*ShutdownMsg)(nil),     // 6: bluetooth_schema.ShutdownMsg
}
var file_bluetooth_msg_proto_depIdxs = []int32{
	4, // 0: bluetooth_schema.BluetoothPacket.request:type_name -> bluetooth_schema.Request
	3, // 1: bluetooth_schema.BluetoothPacket.response:type_name -> bluetooth_schema.Response
	0, // 2: bluetooth_schema.Request.type:type_name -> bluetooth_schema.MsgType
	5, // 3: bluetooth_schema.Request.unlockMsg:type_name -> bluetooth_schema.UnlockMsg
	6, // 4: bluetooth_schema.Request.shutdownMsg:type_name -> bluetooth_schema.ShutdownMsg
	1, // 5: bluetooth_schema.ShutdownMsg.type:type_name -> bluetooth_schema.ShutdownType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_bluetooth_msg_proto_init() }
func file_bluetooth_msg_proto_init() {
	if File_bluetooth_msg_proto != nil {
		return
	}
	file_bluetooth_msg_proto_msgTypes[0].OneofWrappers = []any{
		(*BluetoothPacket_Request)(nil),
		(*BluetoothPacket_Response)(nil),
	}
	file_bluetooth_msg_proto_msgTypes[2].OneofWrappers = []any{
		(*Request_UnlockMsg)(nil),
		(*Request_ShutdownMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bluetooth_msg_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bluetooth_msg_proto_goTypes,
		DependencyIndexes: file_bluetooth_msg_proto_depIdxs,
		EnumInfos:         file_bluetooth_msg_proto_enumTypes,
		MessageInfos:      file_bluetooth_msg_proto_msgTypes,
	}.Build()
	File_bluetooth_msg_proto = out.File
	file_bluetooth_msg_proto_rawDesc = nil
	file_bluetooth_msg_proto_goTypes = nil
	file_bluetooth_msg_proto_depIdxs = nil
}
