// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"fadacontrol/internal/base/conf"
	"fadacontrol/internal/base/data"
	"fadacontrol/internal/service/update_service"
)

// Injectors from wire.go:

func InitRfuctApplication(_conf *conf.Conf, _dbConf *conf.DatabaseConf) (*RfuctApp, error) {
	db, err := data.NewDB(_dbConf)
	if err != nil {
		return nil, err
	}
	updateService := update_service.NewUpdateService(db)
	rfuctApp := NewRfuctApp(_conf, _dbConf, updateService)
	return rfuctApp, nil
}

// wire.go:

type RfuctApp struct {
	_conf   *conf.Conf
	_dbConf *conf.DatabaseConf
	_up     *update_service.UpdateService
}

func NewRfuctApp(_conf *conf.Conf, _dbConf *conf.DatabaseConf, _up *update_service.UpdateService) *RfuctApp {
	return &RfuctApp{_conf: _conf, _dbConf: _dbConf, _up: _up}
}
