// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"fadacontrol/internal/base/bootstrap"
	"fadacontrol/internal/base/conf"
	"fadacontrol/internal/base/data"
	"fadacontrol/internal/base/logger"
	"fadacontrol/internal/controller"
	"fadacontrol/internal/router"
	"fadacontrol/internal/service/common_service"
	"fadacontrol/internal/service/control_pc"
	"fadacontrol/internal/service/credential_provider_service"
	"fadacontrol/internal/service/custom_command_service"
	"fadacontrol/internal/service/remote_service"
	"fadacontrol/internal/service/unlock"
)

// Injectors from wire.go:

func initDesktopServiceApplication(_conf *conf.Conf, db *conf.DatabaseConf) (*DesktopServiceApp, error) {
	loggerLogger := logger.NewLogger(_conf)
	credentialProviderService := credential_provider_service.NewCredentialProviderService()
	gormDB, err := data.NewDB(db)
	if err != nil {
		return nil, err
	}
	chanGroup := conf.NewChanGroup()
	controlPCService := control_pc.NewControlPCService(chanGroup)
	unLockService := unlock.NewUnLockService(credentialProviderService)
	remoteService := remote_service.NewRemoteService(controlPCService, unLockService, _conf, gormDB)
	remoteConnectBootstrap := bootstrap.NewRemoteConnectBootstrap(_conf, gormDB, remoteService)
	customCommandService := custom_command_service.NewCustomCommandService(_conf)
	internalService := common_service.NewInternalService(customCommandService)
	internalServiceBootstrap := bootstrap.NewInternalServiceBootstrap(internalService)
	daemonBootstrap := bootstrap.NewDaemonBootstrap(chanGroup, _conf)
	dataData := data.NewData(gormDB)
	bleUnlockBootstrap := bootstrap.NewBleUnlockBootstrap(unLockService)
	discoverBootstrap := bootstrap.NewDiscoverBootstrap(gormDB)
	remoteController := controller.NewRemoteController(gormDB, remoteService)
	unlockController := controller.NewUnlockController(unLockService)
	controlPCController := controller.NewControlPCController(controlPCService)
	discoverController := controller.NewDiscoverController(gormDB)
	adminRouter := router.NewAdminRouter(remoteController, unlockController, controlPCController, discoverController)
	customCommandController := controller.NewCustomCommandController(_conf, customCommandService)
	commonRouter := router.NewCommonRouter(customCommandController, unlockController, controlPCController)
	httpBootstrap := bootstrap.NewHttpBootstrap(_conf, gormDB, adminRouter, commonRouter)
	legacyControlService := control_pc.NewLegacyControlService(controlPCService, unLockService)
	legacyBootstrap := bootstrap.NewLegacyBootstrap(unLockService, gormDB, legacyControlService)
	desktopServiceBootstrap := bootstrap.NewRootBootstrap(credentialProviderService, remoteConnectBootstrap, internalServiceBootstrap, daemonBootstrap, _conf, dataData, loggerLogger, bleUnlockBootstrap, discoverBootstrap, httpBootstrap, legacyBootstrap)
	desktopServiceApp := NewDesktopServiceApp(loggerLogger, _conf, db, desktopServiceBootstrap)
	return desktopServiceApp, nil
}

func initDesktopDaemonApplication(_conf *conf.Conf, db *conf.DatabaseConf) (*DesktopDaemonApp, error) {
	loggerLogger := logger.NewLogger(_conf)
	customCommandService := custom_command_service.NewCustomCommandService(_conf)
	internalService := common_service.NewInternalService(customCommandService)
	internalServiceBootstrap := bootstrap.NewInternalServiceBootstrap(internalService)
	desktopDaemonBootstrap := bootstrap.NewDesktopDaemonBootstrap(_conf, loggerLogger, internalServiceBootstrap)
	desktopDaemonApp := NewDesktopDaemonApp(loggerLogger, _conf, db, desktopDaemonBootstrap)
	return desktopDaemonApp, nil
}
