// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"fadacontrol/internal/base/bootstrap"
	"fadacontrol/internal/base/conf"
	"fadacontrol/internal/base/data"
	"fadacontrol/internal/base/logger"
	"fadacontrol/internal/base/middleware"
	"fadacontrol/internal/controller/admin_controller"
	"fadacontrol/internal/controller/common_controller"
	"fadacontrol/internal/router/admin_router"
	"fadacontrol/internal/router/common_router"
	"fadacontrol/internal/service/auth_service"
	"fadacontrol/internal/service/control_pc"
	"fadacontrol/internal/service/credential_provider_service"
	"fadacontrol/internal/service/custom_command_service"
	"fadacontrol/internal/service/discovery_service"
	"fadacontrol/internal/service/http_service"
	"fadacontrol/internal/service/internal_service"
	"fadacontrol/internal/service/jwt_service"
	"fadacontrol/internal/service/remote_service"
	"fadacontrol/internal/service/unlock"
	"fadacontrol/internal/service/user_service"
)

// Injectors from wire.go:

func initDesktopServiceApplication(_conf *conf.Conf, db *conf.DatabaseConf) (*DesktopServiceApp, error) {
	loggerLogger := logger.NewLogger(_conf)
	profilingBootstrap := bootstrap.NewProfilingBootstrap(_conf)
	gormDB, err := data.NewDB(db)
	if err != nil {
		return nil, err
	}
	controlPCService := control_pc.NewControlPCService(gormDB)
	adapter, err := data.NewAdapterByDB(gormDB)
	if err != nil {
		return nil, err
	}
	enforcer, err := data.NewEnforcer(adapter)
	if err != nil {
		return nil, err
	}
	dataInitBootstrap := bootstrap.NewDataInitBootstrap(adapter, enforcer, gormDB)
	credentialProviderService := credential_provider_service.NewCredentialProviderService(gormDB)
	unLockService := unlock.NewUnLockService(credentialProviderService)
	remoteService := remote_service.NewRemoteService(controlPCService, unLockService, _conf, gormDB)
	remoteConnectBootstrap := bootstrap.NewRemoteConnectBootstrap(_conf, gormDB, remoteService)
	internalMasterService := internal_service.NewInternalMasterService(controlPCService)
	dataData := data.NewData(gormDB)
	bleUnlockBootstrap := bootstrap.NewBleUnlockBootstrap(unLockService)
	discoverService := discovery_service.NewDiscoverService(gormDB)
	discoverBootstrap := bootstrap.NewDiscoverBootstrap(discoverService)
	httpService := http_service.NewHttpService(gormDB, _conf)
	systemController := common_controller.NewSystemController(controlPCService, _conf)
	jwtService := jwt_service.NewJwtService()
	authService := auth_service.NewAuthService(enforcer)
	jwtMiddleware := middleware.NewJwtMiddleware(jwtService, authService)
	userService := user_service.NewUserService(gormDB)
	authController := common_controller.NewAuthController(userService, jwtService)
	customCommandService := custom_command_service.NewCustomCommandService(_conf)
	customCommandController := common_controller.NewCustomCommandController(_conf, customCommandService)
	unlockController := common_controller.NewUnlockController(unLockService)
	controlPCController := common_controller.NewControlPCController(controlPCService)
	commonRouter := common_router.NewCommonRouter(systemController, jwtMiddleware, authController, customCommandController, unlockController, controlPCController)
	httpController := admin_controller.NewHttpController(gormDB, httpService)
	remoteController := admin_controller.NewRemoteController(gormDB, remoteService)
	discoverController := admin_controller.NewDiscoverController(discoverService)
	adminRouter := admin_router.NewAdminRouter(httpController, systemController, jwtMiddleware, remoteController, unlockController, controlPCController, discoverController, authController)
	httpBootstrap := bootstrap.NewHttpBootstrap(_conf, httpService, commonRouter, adminRouter)
	legacyControlService := control_pc.NewLegacyControlService(controlPCService, unLockService)
	legacyBootstrap := bootstrap.NewLegacyBootstrap(unLockService, gormDB, legacyControlService)
	desktopMasterServiceBootstrap := bootstrap.NewDesktopMasterServiceBootstrap(profilingBootstrap, controlPCService, dataInitBootstrap, credentialProviderService, remoteConnectBootstrap, internalMasterService, _conf, dataData, loggerLogger, bleUnlockBootstrap, discoverBootstrap, httpBootstrap, legacyBootstrap)
	desktopServiceApp := NewDesktopServiceApp(loggerLogger, _conf, db, desktopMasterServiceBootstrap)
	return desktopServiceApp, nil
}

func initDesktopDaemonApplication(_conf *conf.Conf, db *conf.DatabaseConf) (*DesktopSlaveServiceApp, error) {
	loggerLogger := logger.NewLogger(_conf)
	profilingBootstrap := bootstrap.NewProfilingBootstrap(_conf)
	gormDB, err := data.NewDB(db)
	if err != nil {
		return nil, err
	}
	controlPCService := control_pc.NewControlPCService(gormDB)
	adapter, err := data.NewAdapterByDB(gormDB)
	if err != nil {
		return nil, err
	}
	enforcer, err := data.NewEnforcer(adapter)
	if err != nil {
		return nil, err
	}
	dataInitBootstrap := bootstrap.NewDataInitBootstrap(adapter, enforcer, gormDB)
	customCommandService := custom_command_service.NewCustomCommandService(_conf)
	internalSlaveService := internal_service.NewInternalSlaveService(customCommandService, controlPCService, _conf)
	desktopSlaveServiceBootstrap := bootstrap.NewDesktopSlaveServiceBootstrap(profilingBootstrap, controlPCService, dataInitBootstrap, _conf, loggerLogger, internalSlaveService)
	desktopSlaveServiceApp := NewDesktopSlaveServiceApp(loggerLogger, _conf, db, desktopSlaveServiceBootstrap)
	return desktopSlaveServiceApp, nil
}
