name: build for canary

on:
  push:
    branches: release/canary

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up  tools
        run: |
          sudo apt-get install make gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 mingw-w64
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version:  "1.23.4"
      - name: Write date and git commit to file
        run: |
            {
              date -u +%Y%m%d
              git log --pretty=format:'%h' -1
            } > canary.txt
      - name: Build EXE
        run: |
          cd cmd/install-service
          bash build-windows.sh
          cd ../core-service
          bash  build-windows.sh 4.1.0.7 ${{secrets.ME_MAIL}}  windows
          cd ../rfuct
          bash  build-windows.sh
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
           files: "canary.txt"
           prerelease: true
           tag_name: canary
           token: ${{ secrets.GH_TOKEN }}

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: "cmd/core-service/out/*.exe"
          prerelease: true
          tag_name: canary
          token: ${{ secrets.GH_TOKEN }}
          body_path: release_note.md
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: "cmd/install-service/out/*.exe"
          prerelease: true
          tag_name: canary
          token: ${{ secrets.GH_TOKEN }}
          body_path: release_note.md
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: "cmd/rfuct/out/*.exe"
          prerelease: true
          tag_name: canary
          token: ${{ secrets.GH_TOKEN }}
          body_path: release_note.md
      - name: Dispatch cf workflow
        run: |
          curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${{ secrets.CF_HOOK }}
      - name: Dispatch RFU workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/czqu/RemoteFingerUnlock/dispatches \
            -d '{"event_type":"canary"}'