name: build for canary

on:
  push:
    branches: release/canary

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  Download llvm-mingw
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'mstorsjo/llvm-mingw'
          version: 'tags/20240917'
          file: 'llvm-mingw-20240917-ucrt-ubuntu-20.04-x86_64.tar.xz'
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up  tools
        run: |
          tar -xf llvm-mingw-20240917-ucrt-ubuntu-20.04-x86_64.tar.xz
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version:  "1.23.1"
      - name: Write date and git commit to file
        run: |
            {
              date -u +%Y%m%d
              git log --pretty=format:'%h' -1
            } > canary.txt
      - name: Build EXE
        run: |
          export LLVM_PATH=$GITHUB_WORKSPACE/llvm-mingw-20240917-ucrt-ubuntu-20.04-x86_64/bin
          export PATH=$LLVM_PATH:$PATH
          cd cmd/install-service
          bash build-windows.sh
          cd ../core-service
          bash  build-windows.sh 4.0.2.7 ${{secrets.ME_MAIL}}  windows
         
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
           files: "canary.txt"
           prerelease: true
           tag_name: canary
           token: ${{ secrets.GH_TOKEN }}

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: "cmd/core-service/out/*.exe"
          prerelease: true
          tag_name: canary
          token: ${{ secrets.GH_TOKEN }}
          body_path: release_note.md
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: "cmd/install-service/out/*.exe"
          prerelease: true
          tag_name: canary
          token: ${{ secrets.GH_TOKEN }}
          body_path: release_note.md
      - name: Dispatch cf workflow
        run: |
          curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${{ secrets.CF_HOOK }}
      - name: Dispatch RFU workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/czqu/RemoteFingerUnlock/dispatches \
            -d '{"event_type":"canary"}'