name: build for develop

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up  tools
        run: |
          sudo apt-get install make gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 mingw-w64
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version:  "1.23.4"
      - name: Write date and git commit to file
        run: |
          {
            date -u +%Y%m%d
            git log --pretty=format:'%h' -1
          } > canary.txt
      - name: Build EXE
        run: |
          cd cmd/install-service
          bash build-windows.sh
          cd ../core-service
          bash  build-windows.sh 4.1.0.7 ${{secrets.ME_MAIL}}  windows

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-files
          path: ./**/*
          retention-days: 1