name: release build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: get version
        id: get-version
        run: |
          ref="${{ github.ref }}"
          version=$(echo $ref | sed 's|refs/tags/v||')
          echo "CURRENT_VER=v$version" >> $GITHUB_ENV
          echo "CURRENT_VER_NUM=$version" >>  $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up  tools
        run: |
          sudo apt-get install make gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 mingw-w64
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version:  "1.23.3"
      - name: Build EXE
        run: |
          cd cmd/install-service
          bash build-windows.sh
          cd ../core-service
          bash  build-windows.sh ${{ env.CURRENT_VER_NUM }} ${{secrets.ME_MAIL}}  windows
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: "cmd/core-service/out/*.exe"
          make_latest: true
          body_path: release_note.md
          token: ${{ secrets.GH_TOKEN }}
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
         files: "cmd/install-service/out/*.exe"
         make_latest: true
         body_path: release_note.md
         token: ${{ secrets.GH_TOKEN }}